name: Deploy CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids $(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=aspire-app" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text) \
            --document-name "AWS-RunShellScript" \
            --parameters commands="cd /home/ubuntu && docker compose pull && docker compose up -d" \
            --region eu-north-1